pipeline {
  agent {
    docker { image 'node:17-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
        sh 'pwd'
        sh 'df -h'
        sh 'docker version'
        sh 'docker ps -a'
      }
    }
  }
}
